In [3]:
import numpy as np

In [4]:
input = [[1,2,3],
        [1,2,1],
        [0,1,0]]

In [5]:
y = [[1], 
     [0],
     [1]]

In [6]:
np.array(input)

array([[1, 2, 3],
       [1, 2, 1],
       [0, 1, 0]])

In [7]:
inputlayer_neurons = 3
hiddenlayer_neurons = 2 
outputlayer_neurons = 1

In [8]:
np.random.seed(42)

In [9]:
wih = np.round(np.random.uniform(size = (inputlayer_neurons,hiddenlayer_neurons)),decimals=1)

In [10]:
wih

array([[ 0.4,  1. ],
       [ 0.7,  0.6],
       [ 0.2,  0.2]])

In [11]:
bih = np.round(np.random.uniform(size = (1,hiddenlayer_neurons)),decimals=1)

In [12]:
bih

array([[ 0.1,  0.9]])

In [13]:
who = np.round(np.random.uniform(size = (hiddenlayer_neurons,outputlayer_neurons)),decimals=1)

In [14]:
bho = np.round(np.random.uniform(size = (1,outputlayer_neurons)),decimals=1)

In [15]:
who

array([[ 0.6],
       [ 0.7]])

In [16]:
bho

array([[ 0.]])

## Sigmoid Activation Function

In [17]:
def sigmoid(x):
    return 1/(1*np.exp(-x))
    

In [18]:
def derivative_sigmoid(x):
    return x*(1-x)
    

In [19]:
np.random.uniform(size=(3,4))

array([[ 0.96990985,  0.83244264,  0.21233911,  0.18182497],
       [ 0.18340451,  0.30424224,  0.52475643,  0.43194502],
       [ 0.29122914,  0.61185289,  0.13949386,  0.29214465]])

In [20]:
## Multiply input layer with hidden layer
## add the bias to the weithed matrix
## Apply the activation function on the computed values  weights

In [21]:
weigthed_input = np.dot(input,wih)+bih

In [22]:
print(weigthed_input)
print(weigthed_input.shape)

[[ 2.5  3.7]
 [ 2.1  3.3]
 [ 0.8  1.5]]
(3, 2)


In [23]:
%who

bho	 bih	 derivative_sigmoid	 hiddenlayer_neurons	 input	 inputlayer_neurons	 np	 outputlayer_neurons	 sigmoid	 
weigthed_input	 who	 wih	 y	 


In [24]:
hiddenlayer_activations = sigmoid(weigthed_input)

In [25]:
hiddenlayer_activations

array([[ 12.18249396,  40.44730436],
       [  8.16616991,  27.11263892],
       [  2.22554093,   4.48168907]])

In [26]:
hiddenlayer_activation_weighted = np.dot(hiddenlayer_activations,who)+bho
output = sigmoid(hiddenlayer_activation_weighted)

In [27]:
print(output)

[[  2.95598827e+15]
 [  2.34596836e+10]
 [  8.75759929e+01]]


# BackPropargation

1. Calculate the error
2. Calculate the change in error with respect to who
3. Calculate the change in error with respect to bho
4. Calculate the change in error with respect to wih
5. Calculate the change in error with respect to bih
6. Update the who , bho , wih and bih


In [28]:
output

array([[  2.95598827e+15],
       [  2.34596836e+10],
       [  8.75759929e+01]])

In [29]:
#1. Calculate the error
#error =  (y-output)  / 2
error = ( (y-output) * (y-output) ) / 2
error

array([[  4.36893331e+30],
       [  2.75178377e+20],
       [  3.74770127e+03]])

In [40]:
y

[[1, 0, 1]]

In [43]:
output.shape

(3, 1)

In [30]:
#2. Calculate the change in error with respect to who
#    2.1 find change in error wrt output
change_error_wrt_output = y - output
#    2.2 find change in output wrt weighted hidden layer activation
change_output_wrt_weighted_hidden_layer_activation = derivative_sigmoid(output)
#    2.3 find change in weighted hiddenlayer activation wrt who
change_in_weighted_hidden_layer_activation_wrt_who = hiddenlayer_activations
#    2.4 find change in who wrt wh

In [31]:
change_error_wrt_output.shape,change_output_wrt_weighted_hidden_layer_activation.shape,change_in_weighted_hidden_layer_activation_wrt_who.shape


((3, 1), (3, 1), (3, 2))

In [32]:
(change_error_wrt_output * change_output_wrt_weighted_hidden_layer_activation*
change_in_weighted_hidden_layer_activation_wrt_who
).shape


(3, 2)

In [33]:
change_error_wrt_output.shape

(3, 1)

In [34]:
change_output_wrt_weighted_hidden_layer_activation.shape

(3, 1)

In [35]:
(change_error_wrt_output*change_output_wrt_weighted_hidden_layer_activation).shape

(3, 1)

In [36]:
change_in_weighted_hidden_layer_activation_wrt_who.shape

(3, 2)

In [37]:
change_in_weighted_hidden_layer_activation_wrt_who.T.shape

(2, 3)

In [ ]:
(
    change_error_wrt_output*
     change_output_wrt_weighted_hidden_layer_activation
).shape


In [ ]:
change_output_wrt_weighted_hidden_layer_activation.shape

In [ ]:
3. Calculate the change in error with respect to bho
4. Calculate the change in error with respect to wih
5. Calculate the change in error with respect to bih
6. Update the who , bho , wih and bih


In [ ]:
3. Calculate the change in error with respect to bho
4. Calculate the change in error with respect to wih
5. Calculate the change in error with respect to bih
6. Update the who , bho , wih and bih



In [ ]:
3. Calculate the change in error with respect to bho
4. Calculate the change in error with respect to wih
5. Calculate the change in error with respect to bih
6. Update the who , bho , wih and bih
